#21uidwndcasncolma
#asciuasncolxmkzlxc
print(1+1)
print(1+2)
print(1+3,"----third")
print(1+4,"----hot_fix-commit_1")
print(1+5,"----hot_fix-commit_2")
print(1+5,"----master-commit_2")
print(1+6,"----push_test")
print(1+7,"----pull_test")
